name: Set Up Cumulus
description: 'Install CumulusCI and SF CLI'
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: false
  sfdx-version:
    description: 'version of SFDX to install (deprecated - SF CLI will be installed instead)'
    required: false
runs:
    using: "composite"
    steps:
      - name: Set Installable Versions
        id: versions
        uses: nimba-actions/default-package-versions@main
        with:
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'

      - name: Store Versions
        run: |
          echo '${{ steps.versions.outputs.cumulusci-version }}' > actions-cci-version.txt
        shell: bash

      - name: Set Up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install SF CLI
        run: |
          npm install --global @salesforce/cli
          sf --version
          sfdx --version
        shell: bash

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: actions-cci-version.txt

      - name: Install CumulusCI
        run: |
          pip install 'cumulusci==${{ steps.versions.outputs.cumulusci-version }}'
        shell: bash
